# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 3.6
install:
  - pip install mkdocs
  - pip install -r python-requirements.txt
  - echo -e "machine github.com\n  login ${GITHUB_TOKEN}" > ~/.netrc

script: 
  - mkdocs gh-deploy --force
  - git push --force "https://Starxy:${CODING_TOKEN}@git.coding.net/Starxy/MinecraftForge-Documentation-CN.git" gh-pages:master

branches:
  only:
    - master